version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-old-grass-a5aitds5.us-east-2.aws.neon.tech:5432/app_acessibilidade
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: bjG2qO0kCzhP
